//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CK2Tools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CK2Tools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crusader Kings II Tools.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Crusader Kings II installation directory:.
        /// </summary>
        public static string Config_SelectAppDirSmallDlgDesc {
            get {
                return ResourceManager.GetString("Config_SelectAppDirSmallDlgDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crusader Kings II location.
        /// </summary>
        public static string Config_SelectAppDirSmallDlgTitle {
            get {
                return ResourceManager.GetString("Config_SelectAppDirSmallDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find the Crusader Kings II folder defined in the settings..
        /// </summary>
        public static string ConfigError_AppDirNotFound {
            get {
                return ResourceManager.GetString("ConfigError_AppDirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        public static string FileMenu_Config {
            get {
                return ResourceManager.GetString("FileMenu_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Mod.
        /// </summary>
        public static string FileMenu_New {
            get {
                return ResourceManager.GetString("FileMenu_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mod.
        /// </summary>
        public static string FileMenu_Open {
            get {
                return ResourceManager.GetString("FileMenu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string FileMenu_Quit {
            get {
                return ResourceManager.GetString("FileMenu_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Mod.
        /// </summary>
        public static string FileMenu_Save {
            get {
                return ResourceManager.GetString("FileMenu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Global_BtCancel {
            get {
                return ResourceManager.GetString("Global_BtCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Global_BtOK {
            get {
                return ResourceManager.GetString("Global_BtOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ck2 folder..
        /// </summary>
        public static string SetAppDirSimple_CK2NotValid {
            get {
                return ResourceManager.GetString("SetAppDirSimple_CK2NotValid", resourceCulture);
            }
        }
    }
}
